#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Repo 21.02.7发行版

on: 
  # push: 
  #   branches:
  #     - master
   #schedule:
   #  - cron: 30 13 * * 6
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - name: Trigger Compile
      run: |
        sudo timedatectl set-timezone "$TZ"
        if [ ${{ github.event.inputs.ssh }} == 'true' ]; then
          echo "SSH=ssh" >> $GITHUB_ENV
        fi
        curl \
        -X POST https://api.github.com/repos/${{ github.actor }}/${{ github.event.repository.name }}/dispatches \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
        -d '{"event_type": "21.02.7_x86_64  ${{ env.SSH }}", "client_payload": {"target": "21.02.7"}}'




